CREATE TABLE MAHASISWA (
NIM varchar(10),
NAMA varchar(10),
PRODI varchar(10),
BAYAR INT,
PRIMARY KEY (Nim)

);

INSERT INTO MAHASISWA (NIM, NAMA, PRODI, BAYAR)
VALUES 

('A001', 'AB', 'INF', 10),
('A002', 'BC', 'SI', 20),
('A003', 'CD', 'ARS', 15),
('A004', 'DE', 'INF', 30),
('A005', 'EF', 'INF', 10),
('A006', 'F', 'TSP', 25),
('A007', 'G', 'ARS', 15),
('A008', 'H', 'SI', 10);

SELECT PRODI, COUNT(*) AS JUM_MHS
FROM MAHASISWA
group by PRODI;

SELECT PRODI, COUNT(*)
FROM MAHASISWA
GROUP BY PRODI
HAVING COUNT(*)>=3;

SELECT PRODI, SUM(BAYAR) AS JUM_PEMBAYARAN
FROM MAHASISWA
GROUP BY PRODI;

SELECT DISTINCT PRODI FROM MAHASISWA;



SELECT*FROM MAHASISWA;